"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BarChart3, CheckCircle2, ClipboardList, Download, RefreshCw, Send, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";

const ratingItems = [
  "ผลการดำเนินงานโดยรวมเป็นไปตามวัตถุประสงค์ที่กำหนด",
  "กิจกรรมที่เกิดขึ้นจริงสอดคล้องกับสิ่งที่คาดหวังไว้",
  "ผู้เข้าร่วมมีโอกาสแลกเปลี่ยนเรียนรู้และมีส่วนร่วมอย่างเหมาะสม",
  "เวลา บุคลากร และทรัพยากรสนับสนุนการดำเนินงานได้เพียงพอ",
  "ความรู้หรือแนวทางที่ได้รับสามารถนำไปประยุกต์ใช้กับงานได้",
  "ท่านมีความพร้อมที่จะนำบทเรียนหรือนวัตกรรมไปใช้หรือขยายผล",
];

const openQuestions = [
  ["expectation", "ก่อนเริ่มดำเนินงาน ท่านคาดหวังว่าจะเกิดผลลัพธ์อะไร", "ระบุผลที่คาดว่าจะเกิดกับผู้เข้าร่วม หน่วยงาน ผู้เรียน หรือพื้นที่"],
  ["actualResult", "ผลลัพธ์ที่เกิดขึ้นจริงคืออะไร", "ระบุสิ่งที่สังเกตได้ พร้อมตัวอย่างหรือหลักฐานที่เกี่ยวข้อง"],
  ["keep", "สิ่งใดดำเนินการได้ดีและควรรักษาไว้", ""],
  ["gapReason", "ผลที่เกิดขึ้นแตกต่างจากสิ่งที่คาดหวังอย่างไร และเพราะเหตุใด", ""],
  ["successFactor", "ปัจจัยใดมีส่วนสำคัญต่อความสำเร็จของการดำเนินงาน", ""],
  ["obstacle", "ปัญหาหรืออุปสรรคสำคัญคืออะไร และเกิดขึ้นในขั้นตอนใด", ""],
  ["improvement", "หากดำเนินงานอีกครั้ง สิ่งใดควรปรับปรุงเป็นลำดับแรก", ""],
  ["application", "ท่านจะนำความรู้ บทเรียน หรือนวัตกรรมไปประยุกต์ใช้หรือขยายผลอย่างไร", ""],
  ["support", "การนำไปใช้หรือขยายผลต้องได้รับการสนับสนุนด้านใด จากใคร", "เช่น นโยบาย ผู้บริหาร งบประมาณ บุคลากร เวลา คู่มือ ข้อมูล หรือเครือข่าย"],
  ["additional", "ข้อเสนอแนะเพิ่มเติมเพื่อให้การดำเนินงานครั้งต่อไปมีประสิทธิผลมากขึ้น", ""],
] as const;

type ResponseRow = { id:number;createdAt:string;role:string;province:string;participation:string;ratings:number[];expectation:string;actualResult:string;keep:string;gapReason:string;successFactor:string;obstacle:string;improvement:string;application:string;support:string;additional:string;timeline:string;nextAction:string;adoptionStatus:string;successIndicator:string };
const emptyForm = { role:"",province:"",participation:"",ratings:Array(6).fill(0),expectation:"",actualResult:"",keep:"",gapReason:"",successFactor:"",obstacle:"",improvement:"",application:"",support:"",additional:"",timeline:"",nextAction:"",adoptionStatus:"",successIndicator:"" };

function FieldChoices({ name, options, value, onChange }:{name:string;options:string[];value:string;onChange:(v:string)=>void}) {
  return <RadioGroup name={name} value={value} onValueChange={onChange} className="choice-grid">{options.map(option=><label key={option} className={`choice ${value===option?"choice-active":""}`}><RadioGroupItem value={option}/><span>{option}</span></label>)}</RadioGroup>;
}
function level(mean:number){if(mean>=4.21)return"มากที่สุด";if(mean>=3.41)return"มาก";if(mean>=2.61)return"ปานกลาง";if(mean>=1.81)return"น้อย";return"น้อยที่สุด"}

export default function Home(){
  const [form,setForm]=useState(emptyForm);const [responses,setResponses]=useState<ResponseRow[]>([]);const [activeTab,setActiveTab]=useState("survey");const [submitting,setSubmitting]=useState(false);const [submitted,setSubmitted]=useState(false);const [error,setError]=useState("");
  const loadResponses=async()=>{try{const res=await fetch("/api/responses",{cache:"no-store"});const data=await res.json();if(res.ok)setResponses(data.responses??[])}catch{}};
  useEffect(()=>{void loadResponses()},[]);
  const stats=useMemo(()=>{const n=responses.length;const averages=ratingItems.map((_,i)=>n?responses.reduce((s,r)=>s+(r.ratings[i]||0),0)/n:0);const sds=averages.map((avg,i)=>n>1?Math.sqrt(responses.reduce((s,r)=>s+Math.pow((r.ratings[i]||0)-avg,2),0)/(n-1)):0);const overall=n?averages.reduce((a,b)=>a+b,0)/averages.length:0;const countBy=(key:keyof ResponseRow)=>Object.entries(responses.reduce<Record<string,number>>((acc,r)=>{const v=String(r[key]||"ไม่ระบุ");acc[v]=(acc[v]||0)+1;return acc},{})).sort((a,b)=>b[1]-a[1]) as [string,number][];return{n,averages,sds,overall,roles:countBy("role"),timelines:countBy("timeline")}},[responses]);
  const setValue=(key:string,value:string)=>setForm(p=>({...p,[key]:value}));const setRating=(index:number,value:number)=>setForm(p=>({...p,ratings:p.ratings.map((v,i)=>i===index?value:v)}));
  async function submit(e:FormEvent){e.preventDefault();setError("");if(!form.role||!form.province||!form.participation||form.ratings.some(v=>!v)||!form.expectation||!form.actualResult||!form.improvement||!form.timeline||!form.nextAction){setError("กรุณาตอบข้อมูลที่มีเครื่องหมาย * ให้ครบถ้วน");return}setSubmitting(true);try{const res=await fetch("/api/responses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await res.json();if(!res.ok)throw new Error(data.error||"บันทึกไม่สำเร็จ");setSubmitted(true);setForm(emptyForm);await loadResponses();window.scrollTo({top:0,behavior:"smooth"})}catch(err){setError(err instanceof Error?err.message:"ไม่สามารถบันทึกคำตอบได้")}finally{setSubmitting(false)}}
  const exportCsv=()=>{const headers=["วันที่เวลา","บทบาท","จังหวัด","การเข้าร่วม",...ratingItems,...openQuestions.map(q=>q[1]),"ระยะเวลาดำเนินการต่อ","สิ่งที่ตั้งใจดำเนินการต่อ","สถานะการนำไปใช้","ตัวชี้วัดการขยายผล"];const rows=responses.map(r=>[r.createdAt,r.role,r.province,r.participation,...r.ratings,...openQuestions.map(q=>r[q[0] as keyof ResponseRow]),r.timeline,r.nextAction,r.adoptionStatus,r.successIndicator]);const csv="\uFEFF"+[headers,...rows].map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="AAR-responses.csv";a.click();URL.revokeObjectURL(a.href)};
  return <main className="min-h-screen bg-[#f4f8fb] text-slate-900"><header className="topbar"><div className="brand"><span className="brand-mark"><Sparkles size={20}/></span><div><strong>AAR Insight</strong><small>ถอดบทเรียนและขยายผลนวัตกรรมทางการศึกษา</small></div></div><span className="save-note">คำตอบจัดเก็บใน Google Drive</span></header><div className="shell"><section className="intro"><div><span className="eyebrow">แบบทบทวนหลังการดำเนินงาน</span><h1>เปลี่ยนประสบการณ์ให้เป็น<br/><em>บทเรียนที่นำไปใช้ได้จริง</em></h1></div><div className="intro-notes"><p>ใช้เวลาประมาณ 7–10 นาที คำตอบนำเสนอในภาพรวมเพื่อพัฒนางาน ไม่ใช้ประเมินผลรายบุคคล</p><p className="data-purpose"><strong>เหตุผลที่เก็บข้อมูลเพิ่มเติม</strong> เพื่อใช้ติดตามการนำบทเรียนไปใช้ วางแผนการสนับสนุน และกำหนดแนวทางขยายผลให้เหมาะกับแต่ละพื้นที่ โดยนำเสนอข้อมูลในภาพรวมและรักษาความลับของผู้ตอบ</p></div></section>
  <Tabs value={activeTab} onValueChange={setActiveTab} className="workspace"><TabsList className="main-tabs"><TabsTrigger value="survey"><ClipboardList size={17}/>กรอกแบบสอบถาม</TabsTrigger><TabsTrigger value="dashboard"><BarChart3 size={17}/>แดชบอร์ดผลตอบ</TabsTrigger></TabsList>
  <TabsContent value="survey">{submitted&&<div className="success"><CheckCircle2/><div><strong>บันทึกคำตอบเรียบร้อยแล้ว</strong><span>ขอบคุณสำหรับบทเรียนที่ช่วยพัฒนางานครั้งต่อไป</span></div><Button variant="outline" onClick={()=>setSubmitted(false)}>ตอบอีกครั้ง</Button></div>}<form onSubmit={submit} className="survey-form">
    <Card className="section-card"><SectionHead no="01" title="ข้อมูลทั่วไป" note="เลือกคำตอบที่ตรงกับท่านมากที่สุด"/><Question title="บทบาทของท่าน" required><FieldChoices name="role" value={form.role} onChange={v=>setValue("role",v)} options={["ผู้บริหารการศึกษา","ผู้บริหารสถานศึกษา","ศึกษานิเทศก์","ครู","บุคลากรทางการศึกษา","อื่น ๆ"]}/></Question><Question title="จังหวัด" required><FieldChoices name="province" value={form.province} onChange={v=>setValue("province",v)} options={["อุดรธานี","เลย","หนองคาย","บึงกาฬ","หนองบัวลำภู","จังหวัดอื่น"]}/></Question><Question title="ลักษณะการเข้าร่วม" required><FieldChoices name="participation" value={form.participation} onChange={v=>setValue("participation",v)} options={["ผู้จัดหรือคณะทำงาน","ผู้นำเสนอผลงาน","ผู้เข้าร่วมกิจกรรม","ภาคีเครือข่าย","อื่น ๆ"]}/></Question></Card>
    <Card className="section-card"><SectionHead no="02" title="การประเมินภาพรวม" note="5 = มากที่สุด · 1 = น้อยที่สุด"/><div className="rating-table"><div className="rating-head"><span>รายการประเมิน</span>{[5,4,3,2,1].map(n=><span key={n}>{n}<small>{n===5?"มากที่สุด":n===1?"น้อยที่สุด":""}</small></span>)}</div>{ratingItems.map((item,i)=><div className="rating-row" key={item}><p><b>{String(i+1).padStart(2,"0")}</b>{item}<i>*</i></p><RadioGroup value={String(form.ratings[i]||"")} onValueChange={v=>setRating(i,Number(v))} className="rating-options">{[5,4,3,2,1].map(n=><label key={n}><RadioGroupItem value={String(n)}/><span>{n}</span></label>)}</RadioGroup></div>)}</div></Card>
    <Card className="section-card"><SectionHead no="03" title="คำถามทบทวนหลังการดำเนินงาน" note="ตอบสั้น กระชับ และระบุตัวอย่างหรือหลักฐานเมื่อทำได้"/>{openQuestions.map(([key,title,hint],i)=><Question key={key} title={`${i+1}. ${title}`} hint={hint} required={["expectation","actualResult","improvement"].includes(key)}><Textarea value={String(form[key as keyof typeof form])} onChange={e=>setValue(key,e.target.value)} placeholder="พิมพ์คำตอบของท่าน..." rows={3}/></Question>)}</Card>
    <Card className="section-card"><SectionHead no="04" title="ความตั้งใจดำเนินการต่อ" note="เปลี่ยนบทเรียนให้เป็นการลงมือทำ"/><Question title="ท่านคาดว่าจะเริ่มนำไปใช้เมื่อใด" required><FieldChoices name="timeline" value={form.timeline} onChange={v=>setValue("timeline",v)} options={["ภายใน 30 วัน","ภายใน 60 วัน","ต้องเตรียมความพร้อมก่อน","ยังไม่แน่ใจ"]}/></Question><Question title="สิ่งที่ตั้งใจดำเนินการต่อ" required><Input value={form.nextAction} onChange={e=>setValue("nextAction",e.target.value)} placeholder="ระบุการดำเนินการที่ชัดเจน"/></Question><Question title="สถานะการนำไปใช้"><FieldChoices name="adoption" value={form.adoptionStatus} onChange={v=>setValue("adoptionStatus",v)} options={["มีแผนชัดเจนแล้ว","เริ่มดำเนินการแล้ว","ยังไม่มีแผน","ยังไม่สามารถนำไปใช้ได้"]}/></Question><Question title="ตัวชี้วัดความสำเร็จของการขยายผล"><Input value={form.successIndicator} onChange={e=>setValue("successIndicator",e.target.value)} placeholder="เช่น จำนวนหน่วยงานที่นำไปใช้ หรือผลลัพธ์ที่เกิดกับผู้เรียน"/></Question></Card>
    {error&&<p className="form-error">{error}</p>}<div className="submit-row"><div><strong>พร้อมส่งคำตอบหรือยัง</strong><span>โปรดตรวจสอบข้อมูลก่อนบันทึก</span></div><Button type="submit" disabled={submitting} size="lg">{submitting?<RefreshCw className="animate-spin"/>:<Send/>}{submitting?"กำลังบันทึก":"ส่งแบบสอบถาม"}</Button></div></form></TabsContent>
  <TabsContent value="dashboard"><div className="dashboard-head"><div><span className="eyebrow">ผลการตอบแบบเรียลไทม์</span><h2>ภาพรวมการถอดบทเรียน</h2></div><div className="dash-actions"><Button variant="outline" onClick={loadResponses}><RefreshCw/>รีเฟรช</Button><Button variant="outline" onClick={exportCsv} disabled={!responses.length}><Download/>ดาวน์โหลด CSV</Button></div></div><div className="kpi-grid"><Kpi label="ผู้ตอบทั้งหมด" value={String(stats.n)} unit="คน"/><Kpi label="คะแนนเฉลี่ยรวม" value={stats.n?stats.overall.toFixed(2):"–"} unit="จาก 5"/><Kpi label="ระดับผลการดำเนินงาน" value={stats.n?level(stats.overall):"รอข้อมูล"} unit="ตามเกณฑ์เอกสาร"/><Kpi label="พร้อมใช้ภายใน 60 วัน" value={stats.n?`${Math.round(responses.filter(r=>["ภายใน 30 วัน","ภายใน 60 วัน"].includes(r.timeline)).length/stats.n*100)}%`:"–"} unit="ของผู้ตอบ"/></div><div className="dash-grid"><Card className="dash-card span-2"><h3>ผลประเมินรายข้อ</h3><p>ค่าเฉลี่ย ส่วนเบี่ยงเบนมาตรฐาน และจำนวนผู้ตอบจริง</p>{ratingItems.map((item,i)=><div className="metric" key={item}><div><span>{item}</span><small>SD {stats.sds[i].toFixed(2)} · n={stats.n}</small></div><div className="metric-bar"><i style={{width:`${stats.averages[i]*20}%`}}/></div><strong>{stats.n?stats.averages[i].toFixed(2):"–"}</strong></div>)}</Card><Card className="dash-card"><h3>ผู้ตอบจำแนกตามบทบาท</h3><p>จำนวนและร้อยละ</p><Distribution rows={stats.roles} total={stats.n}/></Card><Card className="dash-card"><h3>แผนดำเนินการต่อ</h3><p>ช่วงเวลาที่ผู้ตอบตั้งใจเริ่มใช้</p><Distribution rows={stats.timelines} total={stats.n}/></Card><Card className="dash-card span-2"><h3>ข้อค้นพบเชิงคุณภาพ</h3><p>จัดกลุ่มตามกรอบวิเคราะห์ AAR ในเอกสารต้นฉบับ</p><div className="insight-grid">{[["ผลที่เกิดขึ้นจริง","actualResult"],["สิ่งที่ควรรักษา","keep"],["ช่องว่างและสาเหตุ","gapReason"],["อุปสรรคและการปรับปรุง","improvement"],["การประยุกต์ใช้","application"],["การสนับสนุน","support"]].map(([label,key])=><div className="insight" key={key}><strong>{label}</strong>{responses.filter(r=>String(r[key as keyof ResponseRow]||"").trim()).slice(0,2).map(r=><p key={r.id}>“{String(r[key as keyof ResponseRow])}”</p>)}{!responses.some(r=>String(r[key as keyof ResponseRow]||"").trim())&&<small>ยังไม่มีข้อมูล</small>}</div>)}</div></Card></div>{!responses.length&&<div className="empty-state"><BarChart3/><strong>แดชบอร์ดพร้อมรับข้อมูล</strong><p>เมื่อมีผู้ส่งแบบสอบถาม ผลสรุปจะปรากฏที่หน้านี้โดยอัตโนมัติ</p><Button onClick={()=>setActiveTab("survey")}>กรอกคำตอบแรก</Button></div>}</TabsContent></Tabs></div><footer>สำนักงานศึกษาธิการภาค 10 · ระบบถอดบทเรียน AAR</footer></main>
}
function SectionHead({no,title,note}:{no:string;title:string;note:string}){return <div className="section-head"><span>{no}</span><div><h2>{title}</h2><p>{note}</p></div></div>}
function Question({title,hint,required,children}:{title:string;hint?:string;required?:boolean;children:React.ReactNode}){return <div className="question"><label className="question-title">{title}{required&&<i>*</i>}</label>{hint&&<p className="hint">{hint}</p>}{children}</div>}
function Kpi({label,value,unit}:{label:string;value:string;unit:string}){return <Card className="kpi"><span>{label}</span><strong>{value}</strong><small>{unit}</small></Card>}
function Distribution({rows,total}:{rows:[string,number][];total:number}){return <div className="distribution">{rows.length?rows.map(([label,count])=><div key={label}><div><span>{label}</span><b>{count} · {Math.round(count/total*100)}%</b></div><Progress value={count/total*100}/></div>):<p className="no-data">ยังไม่มีข้อมูล</p>}</div>}
